apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.cronjob.name }}
spec:
  schedule: {{ .Values.cronjob.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: {{ .Values.cronjob.name }}
              image: {{ .Values.cronjob.image }}
            envFrom:
              - secretRef:
                  name: recommender-env
          restartPolicy: OnFailure
          