# Default values for anime-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deployment:
  name: anime-api
  replicas: 1
  port: 8080
  labels: anime-api
  selectorLabel: anime-api
  image: registry.gitlab.com/cs302-2023/g2-team3/services/anime/main:3a049ac42c2a7d18f0a3088babe798f8672fefcd

service:
  name: anime
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  name: anime-ingress
  route: /api/v1/anime
