# Default values for anime-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deployment:
  name: recommender-api
  replicas: 1
  port: 5001
  labels: recommender-api
  selectorLabel: recommender-api
  image: registry.gitlab.com/cs302-2023/g2-team3/services/recommender/main:3b2fa1aa185421f0030d0e1200a8bbaa9243665b

service:
  name: recommender
  type: ClusterIP
  port: 80
  targetPort: 5001

ingress:
  name: recommender-ingress
  route: /api/v1/recommendations
