# Default values for anime-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deployment:
  name: recommender-api
  replicas: 1
  port: 5001
  labels: recommender-api
  selectorLabel: recommender-api
  image: registry.gitlab.com/cs302-2023/g2-team3/services/recommender/main:f5159504844e749d9418fbb0e434779dcac96e0f

service:
  name: recommender
  type: ClusterIP
  port: 80
  targetPort: 5001

ingress:
  name: recommender-ingress
  route: /recommender
