apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.app.selectorLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.labels }}
    spec:
      containers:
      - name: {{ .Values.app.name }}
        image: registry.gitlab.com/cs302-2023/g2-team3/services/users/main:ed2e5572cc7a8d9c84e8be4561df2319a55bd681
        ports:
        - containerPort: {{ .Values.app.port }}
        env:
        - name: POSTGRES_CONN
          valueFrom:
            secretKeyRef:
              name: postgres-cred
              key: connection-string