# Default values for anime-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deployment:
  name: watchlist-api
  replicas: 1
  port: 8080
  labels: watchlist-api
  selectorLabel: watchlist-api
  image: registry.gitlab.com/cs302-2023/g2-team3/services/watchlist/main:f6462914fffa28726793485363c151f7696ac3ae

service:
  name: watchlist
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  name: watchlist-ingress
  route: /watchlist
