apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: traefik-monitor
  labels:
    release: prometheus
spec:
  endpoints:
  - path: /metrics
  selector:
    matchLabels:
      app: traefik