apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: user-monitor
  labels:
    release: prometheus-stack
spec:
  endpoints:
  - interval: 15s
    port: web
  selector:
    matchLabels:
      app: user