apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: watchlist-monitor
  labels:
    release: prometheus
spec:
  endpoints:
  - interval: 15s
    port: web
  selector:
    matchLabels:
      app: watchlist