apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: default
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.selectorLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.labels }}
    spec:
      containers:
      - name: {{ .Values.deployment.name }}
        image: {{ .Values.deployment.image }}
        ports:
        - containerPort: {{ .Values.deployment.port }}
        envFrom:
          - secretRef:
              name: recommender-env
        env:
        - name: ANIME_HOST
          value: "http://anime.default.svc.cluster.local:80"