apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: recommender-engine
  namespace: argocd
spec:
  project: default
  source:
    path: manifests/recommender-engine
    repoURL: https://gitlab.com/cs302-2023/g2-team3/charts/charts.git
    targetRevision: HEAD
    helm:
      releaseName: recommender-engine
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true