apiVersion: v1
kind: Secret
metadata:
  name: postgres-cred
type: Opaque
data:
  connection-string: <base-64 encoded> #postgresql://postgres:psas@postgresql:5432/postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-cred
type: Opaque
data:
  amqp-url: <base-64 encoded> #amqp://user:pass@rabbitmq:5672/
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
type: DockerConfigJson
data:
  .dockercfg: <base-64 encoded> # {"auths":{"registry.gitlab.com":{"username":"gitlab+deploy-token","password":"pass"}}}