apiVersion: v1
kind: Secret
metadata:
  name: recommender-env
type: Opaque
stringData:
  stage: "prod"
  db_conn: "postgresql://postgres:f4erI6hggs@postgresql:5432"
  db_name: "postgres"
  rabbitmq_username: "user"
  rabbitmq_password: "X0uN000Op41UgRaZ"
  rabbitmq_hostname: "rabbitmq"
  rabbitmq_port: "5672"
  exchange_name: "recommenderUpdate.topic"
  exchange_type: "topic"
  queue_name: "recommenderEngine"
  routing_key: "interactionDataPush.*"
