apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: registry-credentials
  namespace: argocd
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <Add credentials here>

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: default
imagePullSecrets:
- name: registry-credentials
