apiVersion: batch/v1
kind: CronJob
metadata:
  name: recommender-engine
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: recommender-engine
        spec:
          containers:
            - name: recommender-engine
              image: registry.gitlab.com/cs302-2023/g2-team3/services/cron/main:03e6ae644eb94245b1c03085978019e790ba5eee
              envFrom:
                - secretRef:
                    name: recommender-env
          restartPolicy: Never
          