# Here, an average of 100 requests per second is allowed.
# In addition, a burst of 50 requests is allowed.
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: rate-limit-api
spec:
  rateLimit:
    average: 1000
    burst: 100